### ISSUE TITLE
Add libvt100 to nuget

### ISSUE THREAD

**Issue by tig** [rasmus-toftdahl-olesen/libvt100#15]

**Comment by rasmus-toftdahl-olesen** [comment]
Not a bad idea - i will take a look - it will be a first for me.

**Comment by rasmus-toftdahl-olesen** [comment]
We now have automatic nuget packages when the version number in libvt100.csproj is updated.

https://www.nuget.org/packages/libvt100/

When i see it pop up in the index i will bump the version number to 1.0 and close this issue.

**Comment by rasmus-toftdahl-olesen** [comment]
Works like a charm - libvt100 version 1.0 has now been released!
