### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by weinberg** [rasmus-toftdahl-olesen/libvt100#2]
This library looks great for a project I'm working on but I don't see any licensing info. When I found it on a Google Code archive (https://code.google.com/archive/p/libvt100/)  it says it has an Apache 2 license. Is that still the case? Thanks!

**Comment by rasmus-toftdahl-olesen** [comment]
Hi weinberg, thank you pointing this out, the code is of-course licensed under the Apache 2 license - i have added LICENSE and COPYING files accordingly.

Please let me know what sort of cool things you create using libvt100.
