### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by tig** [rasmus-toftdahl-olesen/libvt100#9]
Posting this in case there was any thought applied previously before I dive in.

Right now, there's no evidence that `libvt100` has any support for tabs (`\t`). IIRC, classic consoles like vt100 defined tabs in terms of tab-stops. 

E.g. `\t' moves cursor to the next tab stop, or to the right margin if there are no more tab stops.

This is also how modern code editors work. Screenshot from VS Code:
![image](https://user-images.githubusercontent.com/585482/80636672-11774280-8a1b-11ea-9564-c2f3e5ea3a51.png)

Here's how `winprint` currently renders this, showing the problem:
![image](https://user-images.githubusercontent.com/585482/80636720-205df500-8a1b-11ea-8bea-5f35cfbedbbc.png)

Approach I'm considering:

On `Input` convert `\t` in the input stream into the right number of spaces to ensure text that follows starts at the next tab stop. 
   
The screen buffer will have lost the fact that the tabs were there. No different than how `\n` is handled now though.

To address this, an enhancement could be added such that on `Input` we keep track of where `\t` were and force renderers to decode and and place correctly (e.g. by extending `Run` to have a `startsWithTab` field).

**Comment by tig** [comment]
https://terminalguide.namepad.de/seq/a_c0-i/

**Comment by tig** [comment]
See #12

**Comment by rasmus-toftdahl-olesen** [comment]
It feels wrong to change the input stream - but i can not think of any better way of doing it - now we just need to wrestle over the correct number of spaces ;)

**Comment by rasmus-toftdahl-olesen** [comment]
Merged Charlie's pull-request with the fix.

**Comment by tig** [comment]
FWIW, this is what I made with this:

https://github.com/tig/winprint/releases/tag/v2.0.4.100

**Comment by rasmus-toftdahl-olesen** [comment]
Hi Charlie

Thank you for sharing your work - it looks really good - and actually
something that i could see my self using, i have tried printing source code
a few times and have always felt that i spent all my time battling editor
options and printers that printed too small or too large for me to use it.

But with WinPrint open sourced, what are you then going to do for a living?

It has been nice to see that someone could actually use some code i wrote X
amount of years ago.
